# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];


  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/3271c860-3a17-44ba-b4a9-a5232d88fda7";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/4262-6D69";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home" =
    {
      device = "/dev/disk/by-uuid/834fdba9-5ec0-4270-ad02-3b2804452b28";
      fsType = "btrfs";
    };

  swapDevices = [
    {
      device = "/dev/disk/by-uuid/1bff8e8d-e586-4d51-8cdb-d73898fd7b77";
    }
  ];


  fileSystems."/drives/steam" =
    {
      device = "/dev/disk/by-uuid/709d872b-2a86-470e-9ebc-fbf73c12b973";
      fsType = "btrfs";
    };

  fileSystems."/drives/bulk" =
    {
      device = "/dev/disk/by-uuid/37dc177f-fb4c-4c90-8610-0395c2fd8278";
      fsType = "btrfs";
    };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
