# Coolium

hide_ascii      = false
key_color       = "Blue"
separator       = "-"
separator_color = "Yellow"

[palette]
type            = "Full"
glyph           = "●"
spacing         = 1
visible         = true

[bar]
glyph           = "●"
symbol_open     = '('
symbol_close    = ')'
visible         = false
hide_delimiters = true

[box]
title           = "Help"
border          = "rounded"
visible         = false

[box.inner_margin]
x               = 2
y               = 1

[custom_ascii]
path = "/home/coolgi/.dotfiles/ascii/nix-trans.ascii"

[randomize]
key_color       = false
separator_color = false
pool            = "base"

